steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - site-visit-api
  - --region=us-east1
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --entry-point=increment
  - --allow-unauthenticated